version: '3'

services:
  db:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: total_solution
      MYSQL_PASSWORD: Salo2022.
      MYSQL_ROOT_PASSWORD: Salo2022.
    ports:
      - "3306:3306"
    #volumes:
    #  - ./mysql:/var/lib/mysql
    restart: always
    
  web:
    build: ./docker/web
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: db